name: Workflow set 1
on:
  - push
jobs:
  Example-Job-1:
    runs-on: ubuntu-20.04
    steps:
      - name: Get files first
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello World!"
      - name: List Files
        run: ls -la /
      - name: List Files in repo
        run: ls -la ${{ github.workspace }}
      - name: Display vars
        run: env
