name: Test GitHub Actions
on:
  - push
jobs:
  Other-Job-1:
    runs-on: ubuntu-20.04
    steps:
      - run: sleep 30
      - run: sleep 30
      - run: sleep 30
  Other-Job-2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - run: sleep 60
      - run: sleep 60
